language: node_js
node_js: 
  - 13 
services: 
  - docker
install: 
 - echo "nothing needs to be installed"


script:
  - docker version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed abanobmorgan/udagram-api-feed
  - docker tag udagram-api-user abanobmorgan/udagram-api-user
  - docker tag udagram-frontend abanobmorgan/udagram-frontend
  - docker tag udagram-reverseproxy abanobmorgan/udagram-reverseproxy
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push abanobmorgan/udagram-api-feed
  - docker push abanobmorgan/udagram-api-user
  - docker push abanobmorgan/udagram-frontend
  - docker push abanobmorgan/udagram-reverseproxy
